# Simple application with service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: who
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: localhost:5010/tc/whoami:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: testwho
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
  type: NodePort