# Simple application with service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steph-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elp
  template:
    metadata:
      labels:
        app: elp
    spec:
      containers:
      - name: web
        image: nginx:1.19

---
apiVersion: v1
kind: Service
metadata:
  name: prout
spec:
  selector:
    app: elp
  ports:
  - port: 80
    targetPort: 80
  type: NodePort